<?xml version="1.0" encoding="utf-8"?><Database Name="IMEDUBAIFILE" Class="dbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=185.157.41.202;Initial Catalog=IMEDUBAIFILE;Persist Security Info=True;User ID=sa" SettingsObjectName="blutKlinik.Properties.Settings" SettingsPropertyName="IMEDUBAIFILEConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Worker" Member="Workers">
    <Type Name="Worker">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Surname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Telephone" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="Mail" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TitleName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>